### ISSUE TITLE
 Max length is 82, but sentence was 83 bytes

### ISSUE THREAD

**Issue by tomy983** [LORD-MicroStrain/ntrip_client#12]
Hello,
I am getting this error:

[WARN] [1653561112.259201]: Received invalid NMEA sentence. Max length is 82, but sentence was 83 bytes
[WARN] [1653561112.265636]: Sentence: $GNGGA,103152.20,4428.99495,N,01321.79791,E,4,12,0.95,1313.0,M,47.0,M,32.2,0033*63

Sometimes it counts 84 bytes... I don't understand the reason...
i tried to increase max lenght, to 83, still happens...

After a several warnings like that then this happens:
[DEBUG] [1653561203.373171]: Read 0 bytes
[WARN] [1653561203.455948]: Unable to send NMEA sentence to server.
[WARN] [1653561203.459834]: Exception: [Errno 32] Broken pipe

**Comment by robbiefish** [comment]
Hi @tomy983,

Thanks for posting this issue. Looking at the sentence you provided, I believe that the node is responding properly. The max NMEA sentence length is 82 characters. Also when I compute the checksum for the sentence, I get `62`, but you appear to have `63` for a checksum. Where are you sourcing this NMEA sentence from? I would check that it is producing valid NMEA sentences.

**Comment by tomy983** [comment]
Hi @robbiefish,
thanks for your response. Sorry, I did not inform you but I changed coordinates for privacy  before posting, and this is the reason why the checksum is wrong now. it actually is correct in reality. It comes from a ZED-F9P.

i actually just found a way to sort this out and was testing it. I was also trying to fix the broken pipe thing. I will post you a pull request with the minor changes I made.
#13

**Comment by tomy983** [comment]
#13 #

**Comment by tomy983** [comment]
Hey @robbiefish,
I've made a few changes to the client, mostly to handle connection loss and 0 bytes received from NTRIP server. I've tested it and is now working well. Not the best code for sure, but if you want I can create a pull request. 
https://github.com/tomy983/ntrip_client
