### ISSUE TITLE
ROS2 Timer does not support shutdown and join

### ISSUE THREAD

**Issue by PhilippPolterauer** [LORD-MicroStrain/ntrip_client#4]
There is an issue regarding this two lines
https://github.com/LORD-MicroStrain/ntrip_client/blob/eb06b00523e3116c05c9dc2504e8884d91a0798e/scripts/ntrip_ros.py#L78
https://github.com/LORD-MicroStrain/ntrip_client/blob/eb06b00523e3116c05c9dc2504e8884d91a0798e/scripts/ntrip_ros.py#L79

ROS2 Timer does not support the two functions

I suggest removing them. Otherwise the ntrip client does not exit cleanly.

**Comment by robbiefish** [comment]
Thanks for reporting this. The linked PR should fix the issue, but please let me know if it does not.

**Comment by robbiefish** [comment]
Closing as this appears to be resolved. Please reopen if you are still experiencing issues with this
